CREATE TABLE IF NOT EXISTS Employee ( id BIGINT AUTO_INCREMENT PRIMARY KEY, firstname VARCHAR(100), lastname VARCHAR(100), role VARCHAR(20))
CREATE TABLE IF NOT EXISTS Manager ( manager_id BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(100))
